services:
     web:
        image: front-app
        container_name: react-c1
        ports:
           - "3000:3000"
     app:
        image: back-app
        container_name: api-c1
        ports:
           - "5000:5000"
        depends_on:
           - mysql
     mysql:
        image: mysql-app
        container_name: db
        ports:
           - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_db
        volumes:
            -mount_data: /var/lib/mysql

volumes:
    mount_data: 
